### ISSUE TITLE
NVM documentation improvements

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/docs-legacy#56]
The docs repository of Nevermined must be a key point to communicate how users can use/integrate Nevermined. Currently this documentation is disperse, not up to date and not complete. 

The main motivation of this epic is to prepare a documentation portal where we have from top to bottom all the information required about Nevermined. Attracting users to Nevermined and facilitate the protocol adoption is key, so the documentation must be clear, easy to understand and facilitate users adoption and DevExp.

Tasks:

- [x] https://github.com/nevermined-io/docs/issues/46
- [x] https://github.com/nevermined-io/internal/issues/229
- [x] All the documentation must be consolidated in the docs website
- [x] We must have documentation explaining the core protocol
- [x] We must have good documentation about CLI
- [x] We must have good documentation about contracts
- [x] We must have good documentation about sdk-js
- [x] We must have good documentation about the components catalog
- [x] https://github.com/nevermined-io/sdk-js/issues/149

**Comment by r-marques** [comment]
Some of my thoughts about what the documentation should look like.

### References

- [Docusarus Site Showcase](https://docusaurus.io/showcase)
- [ionic docs](https://ionicframework.com/docs/): Built with docusarus, simple design, easy on the eyes, well structured
---

- Remove the docs landing page. I think the user should be faced directly with an overview of the documentation ("Introduction to nevermined)
- Keep it simple and reduce nesting
- Make better use of navigation and organization of the docs. We have a sidebar and a navbar that we can use
- Have better design, smaller found size, specially in the sidebar
- Improve how to the code is displayed to be easier to read (color and monospace font)
- The sidebar should contain several top level sections
```text
- Getting Started
    - Overview (what is nevermined)
    - ...
    - Next Steps: -> Catalog or -> sdk
- Nevermined SDK
    - Overview
    - Getting Started
        - Connecting to nevermined
        - Minting an NFT
        - ...
    - Understanding the gateway
        - Simple overview and link to architecture docs
        - The gatewayAddress and gatewayUrl
        - Urls and access control
        - Delegation with examples
    - Understanding the markeplace
        - Simple overview and link to architecture docs
        - The marketplace uri and login
        - Metadata with examples
    - Code Reference:
        - Nevermined main class
        - NFTs
        - Assets
        - Events
        - ...
- Catalog
    - ....
- CLI
- REST Apis
    - marketplace
    - gateway
- Architecture
- Specs
